[theme]
base = "dark"
primaryColor = "#8e2de2"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#f5f5f5"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false